#!/bin/sh

NGINX="/opt/sbin/nginx"
PID_FILE="/var/run/nginx.pid"
NGINX_ARGS="-c /opt/etc/nginx/nginx.conf"

case "$1" in
  start)
	mkdir -p /var/log/nginx /var/tmp/nginx
	start-stop-daemon -S -m -b -p "$PID_FILE" --exec "$NGINX" -- $NGINX_ARGS
	;;
  stop)
	start-stop-daemon -K -q -p "$PID_FILE" -o
	;;
  reload|force-reload)
	"$NGINX" -s reload
	;;
  restart)
	"$0" stop
	# this allows a graceful restart of service by actually waiting for it to stop first
	service_pid="$(cat $PID_FILE 2> /dev/null)"
	if [ -n "$service_pid" ]; then
		while true; do
				if [ ! -d /proc/"$service_pid" ] ; then
					break
				fi
		done
	fi
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}"
	exit 1
esac
