#!/bin/sh

PID_FILE=/run/ustreamer.pid

case "$1" in
  start)
    V4L_DEVICE=$(v4l2-ctl --list-devices|grep -A1 usb|sed 's/^[[:space:]]*//g'|grep '^/dev' | head -1)
    if [ "x$V4L_DEVICE" = "x" ]; then
      echo "No webcams found!"
      exit 1
    fi

    LD_LIBRARY_PATH=/opt/lib:/opt/usr/lib start-stop-daemon -S -b -m -p $PID_FILE --exec "/opt/usr/bin/ustreamer" -- -d $V4L_DEVICE -r 1280x720 -m MJPEG --device-timeout=2 -w 1 -I MMAP -c HW -p 8080 -s*
    ;;
  stop)
    start-stop-daemon -K -p $PID_FILE
   [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;

  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage:"
    echo "    $0 {start|stop|restart}"
    exit 1
esac

exit $?
