#!/bin/sh

PID_FILE="/var/run/mjpg_streamer.pid"

case "$1" in
  start)
    V4L_DEVICE=$(v4l2-ctl --list-devices|grep -A1 usb|sed 's/^[[:space:]]*//g'|grep '^/dev' | head -1)
    if [ "x$V4L_DEVICE" = "x" ]; then
      echo "No webcams found!"
      exit 1
    fi

    start-stop-daemon -S -b -m -p $PID_FILE --exec "/opt/bin/mjpg_streamer" -- -i "/opt/lib/mjpg-streamer/input_uvc.so -d $V4L_DEVICE -r 1280x720 -f 15 -n -timeout 15" -o "/opt/lib/mjpg-streamer/output_http.so -p 8080"
    ;;
  stop)
    start-stop-daemon -K -p $PID_FILE
    ;;

  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage:"
    echo "    $0 {start|stop|restart}"
    exit 1
esac

exit $?
