#!/bin/sh

USER_DATA=/usr/data
PROG=/usr/share/klippy-env/bin/python
PY_SCRIPT=/usr/data/klipper/klippy/klippy.py
PRINTER_DATA_DIR=$USER_DATA/printer_data
PRINTER_CONFIG_DIR=$PRINTER_DATA_DIR/config
PRINTER_LOGS_DIR=$PRINTER_DATA_DIR/logs
GCODE_FILES_DIR=$PRINTER_DATA_DIR/gcodes
PID_FILE=/var/run/klippy.pid

start() {
      [ -d $PRINTER_DATA_DIR ] || mkdir -p $PRINTER_DATA_DIR
      [ -d $PRINTER_CONFIG_DIR ] || mkdir -p $PRINTER_CONFIG_DIR
      [ -d $PRINTER_LOGS_DIR ] || mkdir -p $PRINTER_LOGS_DIR
      [ -d $GCODE_FILES_DIR ] || mkdir -p $GCODE_FILES_DIR

      HOME=/root start-stop-daemon -S -q -b -m -p $PID_FILE \
            --exec $PROG -- $PY_SCRIPT \
            $PRINTER_CONFIG_DIR/printer.cfg \
            -l $PRINTER_LOGS_DIR/klippy.log \
            --rotate-log-at-restart \
            -a /tmp/klippy_uds
}

stop() {
      start-stop-daemon -K -q -p $PID_FILE > /dev/null 2>&1
}

restart() {
      stop
      # this allows a graceful restart of service by actually waiting for it to stop first
      service_pid="$(cat $PID_FILE 2> /dev/null)"
      if [ -n "$service_pid" ]; then
            while true; do
                  if [ ! -d /proc/"$service_pid" ] ; then
                        break
                  fi
            done
      fi
      start
}

case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  restart|reload)
      restart
      ;;
  *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac

exit $?
