#!/bin/sh

FLAG_FILE="/tmp/udisk/sda1/emergency_factory_reset"

factory_reset() {
    mv "$FLAG_FILE" "${FLAG_FILE}.old" >/dev/null 2>&1
    
    # skip startup routine
    if [ -f /usr/data/creality/userdata/config/system_config.json ]; then
        sed -i 's/"self_test_sw":1/"self_test_sw":0/' /usr/data/creality/userdata/config/system_config.json
    fi
    
    /usr/bin/mcu_reset.sh >/dev/null 2>&1
    ACTION=stop /usr/bin/auto_uvc.sh >/dev/null 2>&1
    [ -f /etc/init.d/S50nginx_service ] && /etc/init.d/S50nginx_service stop >/dev/null 2>&1
    [ -f /etc/init.d/S99guppyscreen ] && /etc/init.d/S99guppyscreen stop >/dev/null 2>&1
    [ -f /etc/init.d/S50webcam ] && /etc/init.d/S50webcam stop >/dev/null 2>&1
    [ -f /etc/init.d/S56moonraker_service ] && /etc/init.d/S56moonraker_service stop >/dev/null 2>&1
    [ -f /etc/init.d/S55klipper_service ] && /etc/init.d/S55klipper_service stop >/dev/null 2>&1
    /usr/bin/find /overlay/upper/ \
        -path '/overlay/upper/etc/dropbear' -prune -o \
        -path /overlay/upper/etc/localtime -prune -o \
        -path /overlay/upper/etc/init.d/S58factoryreset -prune -o \
        -exec rm {} \; >/dev/null 2>&1
    /bin/sync >/dev/null 2>&1
    /usr/bin/find /overlay/upper/ -type d \
        -depth -print \
        -exec rmdir {} \; >/dev/null 2>&1
    /bin/sync >/dev/null 2>&1
    /usr/bin/find /usr/data/ \
        -path '/usr/data/creality' -prune -o \
        -path '/usr/data/wpa_supplicant.conf' -prune -o \
        -path '/usr/data/pellcorp-overrides.cfg' -prune -o \
        -path '/usr/data/pellcorp-overrides' -prune -o \
        -path '/usr/data/machine_production_info' -prune -o \
        -path '/usr/data/' -o -print \
        -exec rm -rf {} \; >/dev/null 2>&1
    /bin/sync >/dev/null 2>&1
    /usr/bin/find /usr/data/creality/userdata \
        -path '/usr/data/creality/userdata/config/system_config.json' -prune -o \
        -path '/usr/data/creality/userdata/user_agree_root' -prune -o \
        -path '/usr/data/creality/userdata' -o -type d -o -print \
        -exec rm {} \; >/dev/null 2>&1
    /bin/sync >/dev/null 2>&1
    rm -rf /overlay/upper/usr/data/
    /bin/sync >/dev/null 2>&1
    rm -rf /overlay/upper/usr/share/
    /bin/sync >/dev/null 2>&1
    /usr/bin/find /usr/data/creality/ \
        -depth -print \
        -exec rmdir {} \; >/dev/null 2>&1
    /bin/sync >/dev/null 2>&1
    # this is just for my dev board
    sed -i 's/pcba_test/nada/g' /etc/init.d/S55klipper_service
    /bin/sync >/dev/null 2>&1
    echo "Info: Factory reset was executed successfully, the printer will restart..."
    /etc/init.d/rcK >/dev/null 2>&1
    /bin/sync >/dev/null 2>&1
    /sbin/swapoff -a >/dev/null 2>&1
    /sbin/reboot -f >/dev/null 2>&1
}

case "$1" in
    start)
		if [ -f "$FLAG_FILE" ]; then
			echo "Info: Executing factory reset..."
			factory_reset
		else
            echo "Info: No 'emergency_factory_reset' file found on the USB drive!"
            exit 1
		fi
        ;;
    reset)
		echo "Info: Executing factory reset..."
		factory_reset
        ;;
    *)
        echo "Usage: $0 {start|reset}"
        exit 1
        ;;
esac

exit 0
