#
# SimpleAF GrumpyScreen overrides configuration file
#
# Refer to https://github.com/pellcorp/grumpyscreen/blob/main/grumpyscreen.cfg for default configuration
#
[ui]
prompt_emergency_stop: true
# specify -1 for never
display_sleep_sec: 600
# log levels are info, debug, trace
log_level: info
# comma-separated extruder panel button values
extruder_temp_presets: 190, 200, 220, 230, 240, 260, 280, 300
extruder_temp_default: 230
extruder_length_presets: 5, 10, 15, 20, 25, 30, 35, 45
extruder_length_default: 10
extruder_speed_presets: 1, 2, 5, 10, 15, 20, 22, 25
extruder_speed_default: 5

# blue = primary_colour: 0x2196F3
# green = primary_colour: 0x4CAF50
# pink = primary_colour: 0xFEC5E5
# purple = primary_colour: 0x9C27B0
# red = primary_colour: 0xF44336
# yellow = primary_colour: 0xFFEB3B
[theme]
primary_colour: 0x2196F3
