[update_manager cartotouch]
type: git_repo
path: /usr/data/cartographer-klipper
channel: stable
primary_branch: master
origin: https://github.com/cartographer3d/cartographer-klipper.git
pinned_commit: 7e354f3baa4bcce53251e90c2154727db37c3c5f
is_system_service: False
managed_services: klipper
info_tags:
  desc=Cartographer Probe
