#!/bin/sh

FLAG_FILE="/tmp/udisk/sda1/emergency_factory_reset"

check_for_flag() {
	if [ -f "$FLAG_FILE" ]; then
		# give the wipe data service enough time to start up
		sleep 5
		echo "$1" | nc -U /var/run/wipe.sock
	fi
}

case "$1" in
    start)
        check_for_flag
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit 0
