# this is to enable default k1 cam

# this makes sure the camera appears by default in fluidd and mainsail
# for mechanical probes (bltouch, microprobe, klicky) we use mjpegstreamer at 15fps
# eddy probes (cartographer, beacon, btteddy, etc) are switched to mjpegstreamer-adaptive @ 10fps by the installer
[webcam default]
location: printer
enabled: True
service: mjpegstreamer
flip_horizontal: False
flip_vertical: False
rotation: 0
target_fps: 15
target_fps_idle: 5
stream_url: /webcam/?action=stream
snapshot_url: /webcam/?action=snapshot
