# this is to enable default k1 cam

[webcam default]
location: printer
enabled: True
service: mjpegstreamer
flip_horizontal: False
flip_vertical: False
rotation: 0
target_fps: 15
target_fps_idle: 5
stream_url: /webcam/?action=stream
snapshot_url: /webcam/?action=snapshot
