# ustreamer configuration
[ustreamer]
frames_per_second=10
workers=1
buffers=1
resolution=1280x720
# if your webcam needs to be flipped vertical in webcam.conf, you must also set this to true
# in order for the static images like < CAMERA PAUSED > to show the correct orientation
flip_vertical=false
# https://pellcorp.github.io/creality-wiki/nebula_camera/
disable_nebula_irlight=false
